# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: sample.tsv
coldata: coldata.tsv
condition: condition.tsv

run:
    # Can be a list if pair-end : "R1,R2" or "1,2"
    type: "R1,R2"
    # paired or unpaired fastq file
    reads: "paired"
    # Extension for the input fastq file
    ext: "fastq.gz"

clean:
    # File to remove adapters with trimmomatic
    illuminaclip: "01_Reference/NexteraPE-PE.fa"

ref:
    # Reference Genome (must be unziped)
    genome: "GCF_000001215.4_Release_6_plus_ISO1_MT_genomic.fna"
    # The Hisat index
    index: "04_index/drosophila"
    # gtf file with transcripts
    annotation: "GCF_000001215.4_Release_6_plus_ISO1_MT_genomic.gtf"
    # Gene id for the figures
    geneid: "gene_id"

filtering:
    # Run to remove from the bulk RNA-seq analyse after fastqc introspection (separated by ,) in the cpm_filtering.R script. Can be ""
    #rmrun: "P2598_Ca-1_PVHD16,P2598_Ca-2_PVHD17,P2598_Ca-3_PVHD18,P2598_ScNI-1_PVHD1,P2598_ScNI-2_PVHD2,P2598_ScNI-3_PVHD3,P2598_Sc_At-1_PVHD10,P2598_Sc_At-2_PVHD11,P2598_Sc_At-3_PVHD12,P2598_Sc_Sp-1_PVHD7,P2598_Sc_Sp-2_PVHD8,P2598_Sc_Sp-3_PVHD9"
    rmrun: ""
    #rmproj: "Ca-1,Ca-2,Ca-3,ScNI-1,ScNI-2,ScNI-3,Sc_At-1,Sc_At-2,Sc_At-3,Sc_Sp-1,Sc_Sp-2,Sc_Sp-3"
    rmproj: ""
    # cpm threshold to filter the low expressed genes
    thresh_cpm: 1
    # Minimum number of samples to have a high expressed genes (depending of the cpm threshold)
    thresh_sample: 3

pca:
    labels:
        # columns of sample sheet to use for PCA
        - condition

diffexp:
    # Reference to do the comparison
    ref_level: "Dorsalized"
    # Shrinkage estimator for ranking and visualization (apeglm, normal or ashr)
    lfcshrink_type: "apeglm"
    # Gene name to see the expression between the condition (can be a list of genes)
    gene_name: "Dmel_CR40469,Dmel_CG3620,Dmel_CG4041"
    # Mutant to represent the gene with the top p-value
    mutant_level: "Ventralized"
    # Number of genes to select with the best p-value
    nbpval: 50
    # qvalue threshold
    pCutoff: 0.01
    # Foldchange threshold
    FCcutoff: 1.5

    