# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: sample.tsv
coldata: coldata.tsv
condition: condition.tsv

run:
    # Can be a list if pair-end : "R1,R2" or "1,2"
    type: "R1,R2"
    # paired or unpaired fastq file
    reads: "paired"
    # Extension for the input fastq file
    ext: "fastq.gz"

clean:
    # File to remove adapters with trimmomatic
    illuminaclip: "01_Reference/NexteraPE-PE.fa"

ref:
    # Reference Genome (must be unziped)
    genome: "GCF_000001215.4_Release_6_plus_ISO1_MT_genomic.fna"
    # The Hisat index
    index: "04_index/drosophila"
    # gtf file with transcripts
    annotation: "GCF_000001215.4_Release_6_plus_ISO1_MT_genomic.gtf"
    # Gene id for the figures
    geneid: "gene_id"

filtering:
    # Run to remove from the bulk RNA-seq analyse after fastqc introspection (separated by ,) in the cpm_filtering.R script. Can be ""
    rmrun: ""
    # rmrun: "DKVD7,DKVD8,DKVD9,DKVD10,DKVD11,DKVD12"
    rmproj: ""
    # rmproj: "Ventralized_replicate_1,Ventralized_replicate_2,Ventralized_replicate_3,Ventralized_torso_replicate_1,Ventralized_torso_replicate_2,Ventralized_torso_replicate_3"
    # cpm threshold to filter the low expressed genes
    thresh_cpm: 1
    # Minimum number of samples to have a high expressed genes (depending of the cpm threshold)
    # Take the number of replicat to keep genes with genes only present in one of the condition 
    thresh_sample: 3

pca:
    labels:
        # columns of sample sheet to use for PCA
        - condition

diffexp:
    # Reference to do the comparison
    ref_level: "Dorsalized"
    # Shrinkage estimator for ranking and visualization (apeglm, normal or ashr)
    lfcshrink_type: "apeglm"
    # Gene name to see the expression between the condition (can be a list of genes)
    gene_name: "Dmel_CG8095,Dmel_CG1046,Dmel_CG9885,Dmel_CG1378,Dmel_CG9768,Dmel_CG9559,Dmel_CG2956,Dmel_CG3956"
    # Mutant to represent the gene with the top p-value
    mutant_level: "Dorsalized_torso"
    # Number of genes to select with the best p-value
    nbpval: 50
    # qvalue threshold
    pCutoff: 0.01
    # Foldchange threshold
    FCcutoff: 2

    