
# #################################################################
# 
#        Quality Check and Cleaning of the Transcriptomic data
#              
# #################################################################

## @knitr fast_qc

## fastqc on the data generated by gatc-biotech
#  List of the repository containing the fastq
rep_list=list.files(PATH_DATA)

# browse the list to run fastqc of each samples

for (i in 1:length(rep_list)) {
  REP_LIST <- as.character(rep_list[[i]])
  setwd(file.path(PATH_DATA,REP_LIST))
  shell('echo "fastqc *.bz2"')
  setwd("../../")
}
